export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SALDOS_REQUEST = 'SALDOS_REQUEST';
export const SALDOS_SUCCESS = 'SALDOS_SUCCESS';
export const SALDOS_FAILED = 'SALDOS_FAILED';

export const OPERACIONES_REQUEST = 'OPERACIONES_REQUEST';
export const OPERACIONES_SUCCESS = 'OPERACIONES_SUCCESS';
export const OPERACIONES_FAILED = 'OPERACIONES_FAILED';

export const RETENCIONES_REQUEST = 'RETENCIONES_REQUEST';
export const RETENCIONES_SUCCESS = 'RETENCIONES_SUCCESS';
export const RETENCIONES_FAILED = 'RETENCIONES_FAILED';

export const EXCEDENTES_REQUEST = 'EXCEDENTES_REQUEST';
export const EXCEDENTES_SUCCESS = 'EXCEDENTES_SUCCESS';
export const EXCEDENTES_FAILED = 'EXCEDENTES_FAILED';
