export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_RESET = 'LOGIN_RESET';

export const SALDOS_REQUEST = 'SALDOS_REQUEST';
export const SALDOS_SUCCESS = 'SALDOS_SUCCESS';
export const SALDOS_FAILED = 'SALDOS_FAILED';

export const OPERACIONES_REQUEST = 'OPERACIONES_REQUEST';
export const OPERACIONES_SUCCESS = 'OPERACIONES_SUCCESS';
export const OPERACIONES_FAILED = 'OPERACIONES_FAILED';

export const CURSO_REQUEST = 'CURSO_REQUEST';
export const CURSO_SUCCESS = 'CURSO_SUCCESS';
export const CURSO_FAILED = 'CURSO_FAILED';

export const VIGENTES_REQUEST = 'VIGENTES_REQUEST';
export const VIGENTES_SUCCESS = 'VIGENTES_SUCCESS';
export const VIGENTES_FAILED = 'VIGENTES_FAILED';

export const RETENCIONES_REQUEST = 'RETENCIONES_REQUEST';
export const RETENCIONES_SUCCESS = 'RETENCIONES_SUCCESS';
export const RETENCIONES_FAILED = 'RETENCIONES_FAILED';

export const EXCEDENTES_REQUEST = 'EXCEDENTES_REQUEST';
export const EXCEDENTES_SUCCESS = 'EXCEDENTES_SUCCESS';
export const EXCEDENTES_FAILED = 'EXCEDENTES_FAILED';

export const INDICADORES_REQUEST = 'INDICADORES_REQUEST';
export const INDICADORES_SUCCESS = 'INDICADORES_SUCCESS';
export const INDICADORES_FAILED = 'INDICADORES_FAILED';

export const LOGOUT = 'LOGOUT';

export const DATA_LOADED = 'DATA_LOADED';
