# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "f43ed188-841c-42f5-b0a0-5d415de655b0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # increment_build_number

  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "8e2ae7f455468bc804817a604a331d6cb2fcbdf1",
    build_secret: "7ad83621f26b8341b2c1ebf9756f3509cb6aaab649f6bae6ab317ad51c185ce8"
  )

  slack(
     slack_url: "https://hooks.slack.com/services/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"
  )
end